# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15U1omA9kyh6pXhn5AwSBvfoFRLNQ8S5y
"""

import streamlit as st
import random

# =========================
# KONFIGURASAUN PÁJINA
# =========================
st.set_page_config(
    page_title="Math Adventure - Klase 5",
    page_icon="🧮",
    layout="centered"
)

# =========================
# CSS - DESIGN ATRATIVU
# =========================
st.markdown("""
<style>
    .main {
        background-color: #f5f7ff;
    }

    .title {
        text-align: center;
        font-size: 42px;
        font-weight: bold;
        color: #4B0082;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 20px;
        color: #555555;
        margin-bottom: 25px;
    }

    .score-box {
        background-color: #ffffff;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        box-shadow: 0px 4px 10px rgba(0,0,0,0.10);
    }

    .question-box {
        background-color: #ffffff;
        padding: 25px;
        border-radius: 20px;
        text-align: center;
        box-shadow: 0px 5px 15px rgba(0,0,0,0.12);
        margin-top: 20px;
    }

    .question {
        font-size: 38px;
        font-weight: bold;
        color: #222222;
    }

    .badge {
        background-color: #FFD700;
        padding: 15px;
        border-radius: 15px;
        text-align: center;
        font-size: 25px;
        font-weight: bold;
    }

    .footer {
        text-align: center;
        color: #777777;
        margin-top: 30px;
    }
</style>
""", unsafe_allow_html=True)


# =========================
# TÍTULU
# =========================
st.markdown(
    '<div class="title">🧮 Math Adventure 🚀</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Operasaun Bázika Matemátika - Klase 5</div>',
    unsafe_allow_html=True
)


# =========================
# SESSION STATE
# =========================
if "started" not in st.session_state:
    st.session_state.started = False

if "question_number" not in st.session_state:
    st.session_state.question_number = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "questions" not in st.session_state:
    st.session_state.questions = []

if "answered" not in st.session_state:
    st.session_state.answered = False

if "feedback" not in st.session_state:
    st.session_state.feedback = ""

if "game_finished" not in st.session_state:
    st.session_state.game_finished = False


# =========================
# FUNSAUN KRIA PERGUNTA
# =========================
def generate_question():
    operation = random.choice(["+", "-", "×", "÷"])

    if operation == "+":
        a = random.randint(10, 99)
        b = random.randint(10, 99)
        answer = a + b

    elif operation == "-":
        a = random.randint(20, 99)
        b = random.randint(10, a)
        answer = a - b

    elif operation == "×":
        a = random.randint(2, 12)
        b = random.randint(2, 10)
        answer = a * b

    else:
        b = random.randint(2, 10)
        answer = random.randint(2, 12)
        a = b * answer

    return {
        "a": a,
        "b": b,
        "operation": operation,
        "answer": answer
    }


# =========================
# PÁJINA INICIAL
# =========================
if not st.session_state.started:

    st.markdown("""
    <div class="question-box">
        <h2>🎯 Bem-vindu ba Math Adventure!</h2>
        <p style="font-size:20px;">
        Aprende no joga ho operasaun bázika:
        </p>
        <p style="font-size:25px;">
        ➕ Adisaun &nbsp;&nbsp;
        ➖ Subtrasaun &nbsp;&nbsp;
        ✖️ Multiplikasaun &nbsp;&nbsp;
        ➗ Divizaun
        </p>
        <p style="font-size:18px;">
        Tenki responde perguntas <b>10</b>.
        Pergunta ida = <b>10 pontos</b>.
        Pontuasaun máximu = <b>100 pontos</b>.
        </p>
    </div>
    """, unsafe_allow_html=True)

    st.write("")

    if st.button("🚀 HAHU JOGU", use_container_width=True):

        st.session_state.started = True
        st.session_state.question_number = 1
        st.session_state.score = 0
        st.session_state.questions = [generate_question()]
        st.session_state.answered = False
        st.session_state.feedback = ""
        st.session_state.game_finished = False

        st.rerun()


# =========================
# JOGU
# =========================
elif st.session_state.started and not st.session_state.game_finished:

    # SCORE
    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "📚 Pergunta",
            f"{st.session_state.question_number}/10"
        )

    with col2:
        st.metric(
            "⭐ Pontuasaun",
            st.session_state.score
        )

    with col3:
        st.metric(
            "🏆 Máximu",
            "100"
        )

    # PROGRESS BAR
    progress = (st.session_state.question_number - 1) / 10
    st.progress(progress)

    # PERGUNTA ATUAL
    q = st.session_state.questions[-1]

    st.markdown(
        f"""
        <div class="question-box">
            <p style="font-size:20px;">Pergunta {st.session_state.question_number}</p>
            <div class="question">
                {q["a"]} {q["operation"]} {q["b"]} = ?
            </div>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    # RESPOSTA
    if not st.session_state.answered:

        answer = st.number_input(
            "✏️ Hatán: ",
            min_value=0,
            max_value=1000,
            value=0,
            step=1
        )

        if st.button("✅ VERIFIKA RESPOSTA", use_container_width=True):

            if answer == q["answer"]:

                st.session_state.score += 10
                st.session_state.feedback = (
                    "🎉 PARABÉNS! Resposta loos! +10 pontos ⭐"
                )

            else:

                st.session_state.feedback = (
                    f"❌ Resposta seidauk loos. "
                    f"Resposta loos mak {q['answer']}."
                )

            st.session_state.answered = True
            st.rerun()

    # FEEDBACK
    else:

        if "🎉" in st.session_state.feedback:
            st.success(st.session_state.feedback)
            st.balloons()
        else:
            st.error(st.session_state.feedback)

        # NEXT QUESTION
        if st.session_state.question_number < 10:

            if st.button(
                "➡️ PERGUNTA TUIRMAI",
                use_container_width=True
            ):

                st.session_state.question_number += 1
                st.session_state.questions.append(generate_question())
                st.session_state.answered = False
                st.session_state.feedback = ""

                st.rerun()

        else:

            if st.button(
                "🏁 REMATA JOGU",
                use_container_width=True
            ):

                st.session_state.game_finished = True
                st.rerun()


# =========================
# RESULTADU FINAL
# =========================
else:

    score = st.session_state.score

    st.markdown(
        """
        <div class="question-box">
            <h1>🏆 Jogu Remata!</h1>
            <h2>🎉 Parabéns ba ita!</h2>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    st.metric(
        "⭐ Ita nia Pontuasaun",
        f"{score}/100"
    )

    # BADGE
    if score >= 90:

        badge = "🏆 MATEMÁTIKA MASTER!"
        message = "Excelente! Ita domina operasaun bázika."

    elif score >= 70:

        badge = "🥇 MATEMÁTIKA HERO!"
        message = "Diak loos! Kontinua pratika."

    elif score >= 50:

        badge = "🥈 MATEMÁTIKA EXPLORER!"
        message = "Diak! Ita bele hadia tan ho pratika."

    else:

        badge = "🌱 MATEMÁTIKA BEGINNER!"
        message = "Labele desistir! Aprende no pratika tan."

    st.markdown(
        f"""
        <div class="badge">
            {badge}
            <br>
            <span style="font-size:18px;">{message}</span>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    if st.button("🔄 JOGA FALI", use_container_width=True):

        st.session_state.started = False
        st.session_state.question_number = 0
        st.session_state.score = 0
        st.session_state.questions = []
        st.session_state.answered = False
        st.session_state.feedback = ""
        st.session_state.game_finished = False

        st.rerun()


# =========================
# FOOTER
# =========================
st.markdown(
    """
    <div class="footer">
        📖 Matemátika Klase 5 | Aprende ho Jogu 🎮
    </div>
    """,
    unsafe_allow_html=True
)