# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCq7QjrN2kctIm1PYxVPdCjjOM2sgRQu
"""

```python
import streamlit as st
import random

# ==========================================================
# CONFIGURAÇÃO DA PÁGINA
# ==========================================================
st.set_page_config(
    page_title="Geometria Quest - Klase 5",
    page_icon="📐",
    layout="centered"
)

# ==========================================================
# ESTILO
# ==========================================================
st.markdown("""
<style>
.main-title {
    text-align: center;
    font-size: 42px;
    font-weight: bold;
}

.subtitle {
    text-align: center;
    font-size: 20px;
}

.question-box {
    padding: 20px;
    border-radius: 15px;
    background-color: #f0f7ff;
    border: 2px solid #4a90e2;
    margin-bottom: 20px;
}

.badge {
    padding: 15px;
    border-radius: 15px;
    background-color: #fff3cd;
    text-align: center;
    font-size: 25px;
    font-weight: bold;
}
</style>
""", unsafe_allow_html=True)


# ==========================================================
# DADUS PERGUNTA
# ==========================================================

questions = [

    # ---------- EASY ----------
    {
        "q": "Forma ida-ne'e iha lados hira? 🔺",
        "options": ["2", "3", "4", "5"],
        "answer": "3",
        "explanation": "Triângulu iha lados 3."
    },

    {
        "q": "Retângulu ida iha vértice hira?",
        "options": ["2", "3", "4", "5"],
        "answer": "4",
        "explanation": "Retângulu iha vértice 4."
    },

    {
        "q": "Forma ne'ebé iha lados 4 ho lados hotu hanesan mak saida?",
        "options": ["Triângulu", "Kuadradu", "Pentágonu", "Hexágonu"],
        "answer": "Kuadradu",
        "explanation": "Kuadradu iha lados 4 no lados hotu-naroman hanesan."
    },

    {
        "q": "Pentágonu iha lados hira?",
        "options": ["4", "5", "6", "7"],
        "answer": "5",
        "explanation": "Pentágonu iha lados 5."
    },

    {
        "q": "Hexágonu iha lados hira?",
        "options": ["5", "6", "7", "8"],
        "answer": "6",
        "explanation": "Hexágonu iha lados 6."
    },

    {
        "q": "Kuadradu ida nia ladu 5 cm. Perímetru hira?",
        "options": ["10 cm", "15 cm", "20 cm", "25 cm"],
        "answer": "20 cm",
        "explanation": "Perímetru = 4 × 5 = 20 cm."
    },

    {
        "q": "Retângulu ida nia komprimentu 8 cm no largura 3 cm. Perímetru hira?",
        "options": ["11 cm", "22 cm", "24 cm", "30 cm"],
        "answer": "22 cm",
        "explanation": "P = 2 × (8 + 3) = 22 cm."
    },

    {
        "q": "Kuadradu nia área ho ladu 4 cm mak hira?",
        "options": ["8 cm²", "12 cm²", "16 cm²", "20 cm²"],
        "answer": "16 cm²",
        "explanation": "Área = ladu × ladu = 4 × 4 = 16 cm²."
    },

    # ---------- MEDIUM ----------
    {
        "q": "Retângulu nia área ho komprimentu 7 cm no largura 4 cm mak hira?",
        "options": ["11 cm²", "22 cm²", "28 cm²", "35 cm²"],
        "answer": "28 cm²",
        "explanation": "Área = 7 × 4 = 28 cm²."
    },

    {
        "q": "Ângulu ne'ebé ki'ik liu 90° bolu saida?",
        "options": ["Ângulu reto", "Ângulu agudu", "Ângulu obtuzu", "Ângulu kompletu"],
        "answer": "Ângulu agudu",
        "explanation": "Ângulu agudu ki'ik liu 90°."
    },

    {
        "q": "Ângulu 90° bolu saida?",
        "options": ["Agudu", "Reto", "Obtuzu", "Kompletu"],
        "answer": "Reto",
        "explanation": "Ângulu 90° mak ângulu reto."
    },

    {
        "q": "Ângulu boot liu 90° maibé ki'ik liu 180° bolu saida?",
        "options": ["Agudu", "Reto", "Obtuzu", "Kompletu"],
        "answer": "Obtuzu",
        "explanation": "Ângulu obtuzu boot liu 90° no ki'ik liu 180°."
    },

    {
        "q": "Triângulu ida iha vértice hira?",
        "options": ["2", "3", "4", "5"],
        "answer": "3",
        "explanation": "Triângulu iha vértice 3."
    },

    {
        "q": "Forma ida iha 8 lados. Naran forma ne'e saida?",
        "options": ["Hexágonu", "Heptágonu", "Octógonu", "Pentágonu"],
        "answer": "Octógonu",
        "explanation": "Octógonu iha lados 8."
    },

    # ---------- DEVELOPMENT / CHALLENGE ----------
    {
        "q": "Kuadradu ida nia perímetru 36 cm. Ladu ida nia naruk hira?",
        "options": ["6 cm", "8 cm", "9 cm", "12 cm"],
        "answer": "9 cm",
        "explanation": "36 ÷ 4 = 9 cm."
    },

    {
        "q": "Retângulu ida nia perímetru 30 cm. Komprimentu 10 cm. Largura hira?",
        "options": ["3 cm", "5 cm", "10 cm", "15 cm"],
        "answer": "5 cm",
        "explanation": "30 = 2 × (10 + largura), nune'e largura = 5 cm."
    },

    {
        "q": "Jardín retangular ida iha komprimentu 12 m no largura 5 m. Área hira?",
        "options": ["17 m²", "34 m²", "60 m²", "120 m²"],
        "answer": "60 m²",
        "explanation": "Área = 12 × 5 = 60 m²."
    },

    {
        "q": "Kuadradu nia área 49 cm². Ladu nia naruk hira?",
        "options": ["6 cm", "7 cm", "8 cm", "9 cm"],
        "answer": "7 cm",
        "explanation": "7 × 7 = 49 cm²."
    },

    {
        "q": "Retângulu ida nia área 72 cm². Se largura 8 cm, komprimentu hira?",
        "options": ["7 cm", "8 cm", "9 cm", "10 cm"],
        "answer": "9 cm",
        "explanation": "72 ÷ 8 = 9 cm."
    },

    {
        "q": "Desafio final 🚀: Jardín ida forma kuadradu ho perímetru 40 m. Se fahe ba quadradu 4 hanesan, área quadradu ida-idak hira?",
        "options": ["10 m²", "25 m²", "50 m²", "100 m²"],
        "answer": "25 m²",
        "explanation": "Ladu = 40 ÷ 4 = 10 m. Área total = 100 m². Fahe ba 4: 100 ÷ 4 = 25 m²."
    }
]


# ==========================================================
# SESSION STATE
# ==========================================================

if "started" not in st.session_state:
    st.session_state.started = False

if "question_number" not in st.session_state:
    st.session_state.question_number = 0

if "score" not in st.session_state:
    st.session_state.score = 0

if "answered" not in st.session_state:
    st.session_state.answered = False

if "selected_answer" not in st.session_state:
    st.session_state.selected_answer = None

if "questions" not in st.session_state:
    st.session_state.questions = questions.copy()
    random.shuffle(st.session_state.questions)


# ==========================================================
# HEADER
# ==========================================================

st.markdown(
    '<div class="main-title">📐 GEOMETRIA QUEST</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">🎮 Jogu Matemátika – Klase 5</div>',
    unsafe_allow_html=True
)

st.write("")

# ==========================================================
# START SCREEN
# ==========================================================

if not st.session_state.started:

    st.info("""
    🎯 **Objetivu do jogu**

    Aprende no testa ita-nia koñesimentu kona-ba:
    - 🔺 Forma geométrika
    - 📏 Lados no vértice
    - 📐 Ângulu
    - 📊 Perímetru
    - 🟦 Área
    """)

    st.success("""
    🏆 **Regra do Jogu**

    • Iha pergunta 20.
    • Ita presiza hili resposta ida.
    • Resposta loos fó pontuasaun.
    • Resposta loos mos fó **surpresa** 🎁.
    • Tenta hetan skor aas liu!
    """)

    if st.button("🚀 KOMESA JOGU", use_container_width=True):
        st.session_state.started = True
        st.rerun()

    st.stop()


# ==========================================================
# GAME FINISHED
# ==========================================================

if st.session_state.question_number >= len(st.session_state.questions):

    st.balloons()

    st.markdown("## 🎉 PARABÉNS! JOGU REMATA!")

    st.metric(
        "🏆 SKOR FINAL",
        f"{st.session_state.score} / 20"
    )

    percentage = (st.session_state.score / 20) * 100

    if percentage >= 90:
        badge = "🏆 Mestre Geometria!"
    elif percentage >= 70:
        badge = "🥇 Especialista Geometria!"
    elif percentage >= 50:
        badge = "🥈 Explorador Geometria!"
    else:
        badge = "🌟 Estudante Geometria!"

    st.markdown(
        f'<div class="badge">{badge}</div>',
        unsafe_allow_html=True
    )

    st.write("")

    if st.button("🔄 JOGA FALI", use_container_width=True):
        st.session_state.question_number = 0
        st.session_state.score = 0
        st.session_state.answered = False
        st.session_state.selected_answer = None
        random.shuffle(st.session_state.questions)
        st.rerun()

    st.stop()


# ==========================================================
# CURRENT QUESTION
# ==========================================================

q_number = st.session_state.question_number
current = st.session_state.questions[q_number]

st.progress(
    q_number / len(st.session_state.questions)
)

col1, col2 = st.columns(2)

with col1:
    st.metric("Pergunta", f"{q_number + 1} / 20")

with col2:
    st.metric("🏆 Skor", st.session_state.score)


st.markdown(
    f"""
    <div class="question-box">
    <h3>Pergunta {q_number + 1}</h3>
    <h2>{current["q"]}</h2>
    </div>
    """,
    unsafe_allow_html=True
)


# ==========================================================
# ANSWER
# ==========================================================

if not st.session_state.answered:

    answer = st.radio(
        "👉 Hili resposta loos:",
        current["options"],
        key=f"answer_{q_number}"
    )

    if st.button("✅ VERIFIKA RESPOSTA", use_container_width=True):

        st.session_state.selected_answer = answer
        st.session_state.answered = True

        if answer == current["answer"]:
            st.session_state.score += 1

        st.rerun()


# ==========================================================
# FEEDBACK
# ==========================================================

else:

    if st.session_state.selected_answer == current["answer"]:

        st.success("🎉 LOS! Ita hatán resposta loos!")

        # SURPRISES
        surprises = [
            "🌟 SURPRESA! Ita mak Estrela Geometria!",
            "🎁 SURPRESA! Ita hetan medalha dourada!",
            "🚀 SURPRESA! Ita-nia poder Geometria aumenta!",
            "🏆 SURPRESA! Ita agora mak Mestre Forma!",
            "💎 SURPRESA! Ita hetan diamante matemátika!"
        ]

        st.balloons()

        st.markdown(
            f'<div class="badge">{random.choice(surprises)}</div>',
            unsafe_allow_html=True
        )

        st.write(
            f"💡 **Explicasaun:** {current['explanation']}"
        )

    else:

        st.error("❌ Resposta seidauk loos.")

        st.info(
            f"💡 **Resposta loos:** {current['answer']}"
        )

        st.write(
            f"📚 **Explicasaun:** {current['explanation']}"
        )

    st.write("")

    if q_number + 1 < len(st.session_state.questions):

        if st.button(
            "➡️ PERGUNTA TUIR",
            use_container_width=True
        ):
            st.session_state.question_number += 1
            st.session_state.answered = False
            st.session_state.selected_answer = None
            st.rerun()

    else:

        if st.button(
            "🏁 HATAMA RESULTADU",
            use_container_width=True
        ):
            st.session_state.question_number += 1
            st.rerun()
```